// Re-export from common components
export { default as SearchBar } from '@/components/common/SearchBar'
export type { SearchParams, SegmentConfig } from '@/components/common/SearchBar'
export { default as SearchHeader } from '@/components/common/SearchHeader'
export { PriceRangeSlider } from './PriceRangeSlider'
export { FilterDialog } from './FilterDialog'
export { SortModal } from './SortModal'
export type { FilterType } from './Filters/registry'
export type { SortType } from './Sorts/registry'
export { default as StaysCard } from './StaysCard'
export { default as StaysCardSkeleton } from './StaysCardSkeleton'
export { default as StaysMap } from './StaysMap'
export { default as StaysListHeader } from './StaysListHeader'
export { default as LandingOverlay } from './LandingOverlay'
export { default as StickySelectedChips } from './StickySelectedChips'
export { default as CityPromptsChips } from './CityPromptsChips'
export { default as AIAssistantWindow } from './AIAssistantWindow'
export { default as HotelCard } from './HotelCard'
export { default as ScrollableHotelResults } from './ScrollableHotelResults'
export { default as OutputLoadingComponent } from './OutputLoadingComponent'
export { DealChip } from './DealChip'
export { triggerAssistantPrompt, closeAssistantWindow } from './assistantController'
