import {
    Baby,
    Bed,
    Building,
    Bus,
    BusFront,
    AirVent,
    AlarmClock,
    Armchair,
    ArrowUp,
    Bath,
    Bike,
    Binoculars,
    Box,
    BrushIcon,
    Cake,
    CalendarHeart,
    Car,
    Computer,
    CreditCard,
    ChefHat,
    Clock,
    CookingPot,
    DoorOpen,
    Droplet,
    Dumbbell,
    Ear,
    Eye,
    FireExtinguisher,
    Flame,
    Gamepad2,
    Footprints,
    Heart,
    HeartHandshake,
    Heater,
    Key,
    Laptop,
    Leaf,
    Library,
    Luggage,
    Map as MapIcon,
    MapPin,
    Microwave,
    Moon,
    Mountain,
    Music,
    Newspaper,
    Palette,
    Phone,
    ParkingCircle,
    Pin,
    Plane,
    PlaneLanding,
    PlaneTakeoff,
    Refrigerator,
    RotateCcw,
    Sailboat,
    Search,
    Shield,
    Shirt,
    ShowerHead,
    Snowflake,
    Sparkles,
    Square,
    ShoppingCart,
    TrainFront,
    Tablet,
    Thermometer,
    Toilet,
    TreePine,
    Trees,
    Tv,
    User,
    Users,
    UsersRound,
    Utensils,
    UtensilsCrossed,
    Accessibility,
    Sun,
    Volume,
    WashingMachine,
    Waves,
    Wifi,
    Wind,
    Wine,
    Cigarette,
    Coffee,
    BrushCleaning,
    Check,
    X
} from 'lucide-react'

// Store component references so we can pass size props dynamically
export const LucideIconComponentMap = {
    Heart,
    Baby,
    Users,
    UsersRound,
    User,
    TrainFront,
    Building,
    AirVent,
    AlarmClock,
    Armchair,
    ArrowUp,
    Bath,
    Bike,
    Binoculars,
    Box,
    BrushIcon,
    Computer,
    CreditCard,
    Moon,
    Utensils,
    UtensilsCrossed,
    MapPin,
    Plane,
    PlaneTakeoff,
    ShoppingCart,
    HeartHandshake,
    CalendarHeart,
    Cake,
    Bed,
    Clock,
    Music,
    Newspaper,
    Palette,
    Phone,
    DoorOpen,
    Droplet,
    Dumbbell,
    Ear,
    Eye,
    FireExtinguisher,
    Flame,
    Gamepad2,
    Bus,
    Car,
    Heater,
    Key,
    Laptop,
    Leaf,
    Library,
    Luggage,
    Mountain,
    BusFront,
    PinSafety: Pin,
    Footprints,
    Map: MapIcon,
    PlaneLanding,
    CookingPot,
    ChefHat,
    Microwave,
    ParkingCircle,
    Wheelchair: Accessibility,
    Accessibility,
    Cigarette,
    Coffee,
    Trees,
    Sun,
    Refrigerator,
    RotateCcw,
    Sailboat,
    Search,
    Shield,
    Shirt,
    Shower: ShowerHead,
    Snowflake,
    Sparkles,
    Square,
    Tablet,
    Thermometer,
    Toilet,
    TreePine,
    BrushCleaning,
    Tv,
    Volume,
    WashingMachine,
    Waves,
    Wifi,
    Wind,
    Wine,
    Check,
    X
} as const

export type LucideIconName = keyof typeof LucideIconComponentMap

export function getLucideIcon(name: string, width?: number, height?: number): React.ReactElement | null {
    const Comp = (LucideIconComponentMap as Record<string, any>)[name]
    if (!Comp) return null
    const w = width ?? 16
    const h = height ?? 16
    return (
        <Comp
            width={w}
            height={h}
        />
    )
}
