import {
    Accessibility,
    AirVent,
    AlarmClock,
    Armchair,
    ArrowUp,
    Baby,
    Bath,
    Bed,
    Bike,
    Binoculars,
    Box,
    BrushCleaning,
    BrushIcon,
    Building,
    Bus,
    Car,
    ChefHat,
    Cigarette,
    Circle,
    Coffee,
    Computer,
    CreditCard,
    DoorOpen,
    Droplet,
    Dumbbell,
    Ear,
    Eye,
    FireExtinguisher,
    Flame,
    Gamepad2,
    Heart,
    Heater,
    Key,
    Laptop,
    Leaf,
    Library,
    Luggage,
    Microwave,
    Mountain,
    Music,
    Newspaper,
    Palette,
    Phone,
    Plane,
    Refrigerator,
    RotateCcw,
    Sailboat,
    Search,
    Shield,
    Shirt,
    ShoppingCart,
    ShowerHead,
    Snowflake,
    Sparkles,
    Square,
    Sun,
    Tablet,
    Thermometer,
    Toilet,
    TreePine,
    Tv,
    Users,
    Utensils,
    UtensilsCrossed,
    Volume,
    WashingMachine,
    Waves,
    Wifi,
    Wind,
    Wine
  } from "lucide-react";
  
  // This map connects icon *name strings* to actual components (not preference keys)
  export const LucideIconMap = {
    Accessibility: <Accessibility width={22} height={22} />,
    AirVent: <AirVent width={22} height={22} />,
    AlarmClock: <AlarmClock width={22} height={22} />,
    Armchair: <Armchair width={22} height={22} />,
    ArrowUp: <ArrowUp width={22} height={22} />,
    Baby: <Baby width={22} height={22} />,
    Bath: <Bath width={22} height={22} />,
    Bed: <Bed width={22} height={22} />,
    Bike: <Bike width={22} height={22} />,
    Binoculars: <Binoculars width={22} height={22} />,
    Box: <Box width={22} height={22} />,
    Broom: <BrushIcon width={22} height={22} />,
    Building: <Building width={22} height={22} />,
    Bus: <Bus width={22} height={22} />,
    Car: <Car width={22} height={22} />,
    ChefHat: <ChefHat width={22} height={22} />,
    Cigarette: <Cigarette width={22} height={22} />,
    Circle: <Circle width={22} height={22} />,
    Coffee: <Coffee width={22} height={22} />,
    Computer: <Computer width={22} height={22} />,
    CreditCard: <CreditCard width={22} height={22} />,
    DoorOpen: <DoorOpen width={22} height={22} />,
    Droplet: <Droplet width={22} height={22} />,
    Dumbbell: <Dumbbell width={22} height={22} />,
    Ear: <Ear width={22} height={22} />,
    Eye: <Eye width={22} height={22} />,
    FireExtinguisher: <FireExtinguisher width={22} height={22} />,
    Flame: <Flame width={22} height={22} />,
    Gamepad2: <Gamepad2 width={22} height={22} />,
    Heart: <Heart width={22} height={22} />,
    Heater: <Heater width={22} height={22} />,
    Key: <Key width={22} height={22} />,
    Laptop: <Laptop width={22} height={22} />,
    Leaf: <Leaf width={22} height={22} />,
    Library: <Library width={22} height={22} />,
    Luggage: <Luggage width={22} height={22} />,
    Microwave: <Microwave width={22} height={22} />,
    Mountain: <Mountain width={22} height={22} />,
    Music: <Music width={22} height={22} />,
    Newspaper: <Newspaper width={22} height={22} />,
    Palette: <Palette width={22} height={22} />,
    Phone: <Phone width={22} height={22} />,
    Plane: <Plane width={22} height={22} />,
    Refrigerator: <Refrigerator width={22} height={22} />,
    RotateCcw: <RotateCcw width={22} height={22} />,
    Sailboat: <Sailboat width={22} height={22} />,
    Search: <Search width={22} height={22} />,
    Shield: <Shield width={22} height={22} />,
    Shirt: <Shirt width={22} height={22} />,
    ShoppingCart: <ShoppingCart width={22} height={22} />,
    Snowflake: <Snowflake width={22} height={22} />,
    Sparkles: <Sparkles width={22} height={22} />,
    Square: <Square width={22} height={22} />,
    Sun: <Sun width={22} height={22} />,
    Tablet: <Tablet width={22} height={22} />,
    Thermometer: <Thermometer width={22} height={22} />,
    Toilet: <Toilet width={22} height={22} />,
    TreePine: <TreePine width={22} height={22} />,
    Tv: <Tv width={22} height={22} />,
    Users: <Users width={22} height={22} />,
    Utensils: <Utensils width={22} height={22} />,
    UtensilsCrossed: <UtensilsCrossed width={22} height={22} />,
    Volume: <Volume width={22} height={22} />,
    WashingMachine: <WashingMachine width={22} height={22} />,
    Waves: <Waves width={22} height={22} />,
    Wifi: <Wifi width={22} height={22} />,
    Wind: <Wind width={22} height={22} />,
    Wine: <Wine width={22} height={22} />,
    Shower: <ShowerHead width={22} height={22} />,
    BrushCleaning: <BrushCleaning width={22} height={22} />
  } as const;
  
  // Mapping from amenity names to icon component names
  export const AmenityToIconMap = {
    "accessible": "Accessibility",
    "air_conditioning": "AirVent",
    "airport_shuttle": "Plane",
    "alarm_clock": "AlarmClock",
    "art_gallery": "Palette",
    "art_supplies": "Palette",
    "assistive_listening": "Ear",
    "atm": "CreditCard",
    "balcony": "TreePine",
    "bar": "Wine",
    "barbecue": "Flame",
    "basketball": "Circle",
    "bathrobes": "Shirt",
    "bathtub": "Bath",
    "bed": "Bed",
    "bicycle": "Bike",
    "bicycles": "Bike",
    "bidet": "Toilet",
    "blackout_drapes": "Sun",
    "boat": "Sailboat",
    "boat_tours": "Sailboat",
    "bottled_water": "Droplet",
    "breakfast": "Coffee",
    "business_center": "Building",
    "carpet": "Square",
    "champagne": "Wine",
    "childcare": "Baby",
    "children_amenities": "Baby",
    "children_club": "Baby",
    "children_pool": "Waves",
    "clubhouse": "Building",
    "coffee_maker": "Coffee",
    "computer_station": "Computer",
    "conference_center": "Building",
    "connecting_rooms": "DoorOpen",
    "dining": "Utensils",
    "dinner": "UtensilsCrossed",
    "dishwasher": "WashingMachine",
    "elevator": "ArrowUp",
    "energy_saving": "Leaf",
    "fax": "Phone",
    "fire_extinguisher": "FireExtinguisher",
    "fireplace": "Flame",
    "fishing": "Waves",
    "front_desk": "Users",
    "game_area": "Gamepad2",
    "gift_shop": "ShoppingCart",
    "golf": "Circle",
    "golf_neaby": "Circle",
    "gym": "Dumbbell",
    "hairdryer": "Wind",
    "heater": "Heater",
    "horse_riding": "Mountain",
    "hot_tub": "Waves",
    "hotel_transport": "Bus",
    "housekeeping": "BrushCleaning",
    "hulu": "Tv",
    "ice_maker": "Snowflake",
    "infant_bed": "Baby",
    "ipad": "Tablet",
    "iron": "Shirt",
    "ironing_board": "Shirt",
    "kayaking": "Waves",
    "kayaking_neaby": "Waves",
    "kettle": "Coffee",
    "kitchen": "ChefHat",
    "laundry": "WashingMachine",
    "library": "Library",
    "lifeguard": "Shield",
    "lockers": "Box",
    "luggage_storage": "Luggage",
    "magnifying_mirror": "Search",
    "microwave": "Microwave",
    "minibar": "Wine",
    "mirror": "Eye",
    "mobile_key_entry": "Key",
    "multilingual_staff": "Users",
    "newspaper": "Newspaper",
    "nightclub": "Music",
    "organic_food": "Leaf",
    "parking": "Car",
    "pets_allowed": "Heart",
    "pickleball": "Circle",
    "picnic": "TreePine",
    "garden": "Trees",
    "playground": "Baby",
    "pool": "Waves",
    "pool_table": "Square",
    "private_bathroom": "Toilet",
    "private_beach": "Waves",
    "private_hot_tub": "Waves",
    "private_pool": "Waves",
    "racquetball_squash": "Circle",
    "raised_toilet": "Toilet",
    "recycling": "RotateCcw",
    "refrigerator": "Refrigerator",
    "renewable_energy": "Leaf",
    "restaurant": "UtensilsCrossed",
    "rock_climbing_nearby": "Mountain",
    "room_service": "UtensilsCrossed",
    "safari": "Binoculars",
    "safe": "Shield",
    "sailing": "Sailboat",
    "sauna": "Thermometer",
    "scuba_diving": "Waves",
    "segway_rental": "Bike",
    "shared_bathroom": "Toilet",
    "shower": "Shower",
    "skydiving_nearby": "Plane",
    "smoke": "Cigarette",
    "smoking_area": "Cigarette",
    "snowboarding": "Mountain",
    "soundproofed": "Volume",
    "spa": "Sparkles",
    "stove": "Flame",
    "table_tennis_court": "Square",
    "telephone": "Phone",
    "television": "Tv",
    "tennis": "Circle",
    "tennis_court": "Circle",
    "toiletries": "Droplet",
    "towels": "Shirt",
    "valet": "Users",
    "vending_machine": "ShoppingCart",
    "wardrobe": "Shirt",
    "wheelchair": "Accessibility",
    "wifi": "Wifi",
    "windsurfing": "Wind",
    "wine_tasting": "Wine",
    "winery_attached": "Wine",
    "work_chair": "Armchair",
    "work_desk": "Laptop",
    "work_office": "Building",
    "yoga": "Heart",
    "ziplining_nearby": "Mountain"
  } as const;
  
  // Helper function to get icon by amenity name
  export const getIconByAmenity = (amenityName: string) => {
    const iconName = AmenityToIconMap[amenityName as keyof typeof AmenityToIconMap];
    return iconName ? LucideIconMap[iconName as keyof typeof LucideIconMap] : null;
  };

